import { Inter } from "next/font/google";
import "./globals.css";
import DashNav from "@/components/DashComponents/DashNav";
import LeftSideBar from "@/components/DashComponents/LeftSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashNav />
        <div className="">
          <LeftSideBar />
          <div className="p-8 px-4 lg:ml-72 mt-14 mr-0">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
